#!/bin/sh
[ "$0" == "./system" ] || { echo 'try ./system'; exit; }

usage () {
cat << HEREDOC
USAGE:
    ./system install [OPTIONS]

    Installation will do the following:
        Clone a stable conf to [${conf}]
        Clone a stable borg to [${borg}]
        Install the stable borg.

   Nothing will be overwritten unless overwrite options are supplied.

OPTIONS:
    -b overwrite [${borg}]
    -c overwrite [${conf}]
    -v overwrite [${vard}]
HEREDOC
}

install () {
    for word in $*; do
        [ "$word" == "-b" ] && rm -rf ${borg}
        [ "$word" == "-c" ] && rm -rf ${conf}
        [ "$word" == "-v" ] && rm -rf ${vard}
    done
    [ ! -d ${borg} ] && git clone -b myborg https://github.com/bryanhann/dot.borg            ${borg}
    [ ! -d ${conf} ] && git clone           https://github.com/bryanhann/dot.config.myborg   ${conf}
    echo $this: installing the borg
    >/dev/null pushd ${borg}
    ./install.sh
    >/dev/null popd
    echo $this: restart the system
}

##################################################################
# MAIN
##################################################################

borg=${HOME}/new.borg
conf=~/.config/myborg
vard=~/.local/var/myborg
this=${PWD}/$(basename $0)
case ${1}. in
    install.)
        install $*
        ;;
    *)
        usage
        ;;
esac

