#!/bin/sh


main () {
    [ ! "$1" == "--install" ] && usage || doit $*
}

doit () {
    local borg=${HOME}/new.borg
    local conf=~/.config/myborg
    for word in $*; do
        [ "$word" == "--newborg" ] && rm -rf ${borg}
        [ "$word" == "--newconf" ] && rm -rf ${conf}
    done
    [ ! -d ${borg} ] && git clone -b myborg https://github.com/bryanhann/dot.borg            ${borg}
    [ ! -d ${conf} ] && git clone           https://github.com/bryanhann/dot.config.myborg   ${conf}
    echo 6
    local here=$PWD
    cd ${borg}
    ./install.sh
    cd ${here}
    echo restart.
}

usage () {
cat << HEREDOC
USAGE:
    ./system [--install [ --newborg ] [ --newconf ] ]

    Installation will do the following:
        Clone dot.config.myborg to [~/.config/myborg]
        Clone dot.borg to [~/new.borg]
        Install [~/new.borg]

   Nothing will be overwritten unless overwrite options are supplied.

OPTIONS:
    --install   actually install. This must come first.
    --newborg   overwrite [~/new.borg]
    --newconf   overwrite [~/.config/myborg]

HEREDOC
}

main $*
