#!/bin/sh
[ "$0" == "./system" ] || { echo "try './system'"; exit; }

_export () { export $1=$2; }

_export borg            ${HOME}/new.borg
_export borg_url        https://github.com/bryanhann/dot.borg
_export borg_branch     myborg
_export conf            ~/.config/myborg
_export conf_branch     main
_export conf_url        https://github.com/bryanhann/dot.config.myborg
_export vard            ~/.local/var/myborg

if [ "$1" == "install" ]; then
        for word in $*; do
                [ "$word" == "-b" ] && rm -rf ${borg}
                [ "$word" == "-c" ] && rm -rf ${conf}
        done
        git clone -b ${borg_branch} ${borg_url} ${borg}
        git clone -b ${conf_branch} ${conf_url} ${conf}
        >/dev/null pushd ${borg}
        ./install.sh install $*
        >/dev/null popd
        exit
fi

cat << __HEREDOC
USAGE:
    ./system install [OPTIONS]

    Installation will do the following:
        Clone a stable conf to [${conf}]
        Clone a stable borg to [${borg}]
        Install the stable borg.

   Nothing will be overwritten unless overwrite options are supplied.

OPTIONS:
    -b overwrite [${borg}]
    -c overwrite [${conf}]
    -v overwrite [${vard}]
__HEREDOC

